name: Django tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_NAME: test_db
      DATABASE_USERNAME: test_user
      DATABASE_PASSWORD: test_password
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DJANGO_SECRET_KEY: test_secret_key

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run tests
        run: docker compose --profile test up --build --abort-on-container-exit
        env:
          DATABASE_NAME: ${{ env.DATABASE_NAME }}
          DATABASE_USERNAME: ${{ env.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ env.DATABASE_PASSWORD }}
          DATABASE_HOST: ${{ env.DATABASE_HOST }}
          DATABASE_PORT: ${{ env.DATABASE_PORT }}
          DJANGO_SECRET_KEY: ${{ env.DJANGO_SECRET_KEY }}
